# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2020.

branches:
  only:
    - /master.*/
    - /develop.*/
    - /feature\/.*/

configuration:
  - Test
  - Boost

environment:
  matrix:
  - job_name: 'Visual Studio 2015, Test'
    job_group: 'Test'
    TOOLSET: vc14
    TEST_TOOLSET: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - job_name: 'Visual Studio 2013, Test'
    job_group: 'Test'
    TOOLSET: vc12
    TEST_TOOLSET: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

build_script:
  - ps: |
    cd src/engine
    $env:path += ';' + $env:CXX_PATH
    cmd /c build.bat $env:TOOLSET
    ./b2.exe -v
    cd ../..

before_test:
  -ps: |
    $env:HOME = $env:HOMEDRIVE + $env:HOMEPATH
    echo "using" $env:TEST_TOOLSET ":" ":" $env:CXX ";" > $env:HOME/user-config.jam

for:
  - matrix:
    only:
      - job_group: 'Test'

  test_script:
    - ps: |
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> TEST"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      cd test
      python test_all.py $env:TEST_TOOLSET
      cd ..
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> NO WARNINGS"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      ./src/engine/b2.exe --debug-configuration b2 warnings-as-errors=on toolset=$env:TEST_TOOLSET
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> BOOTSTRAP"
      echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      ./bootstrap.bat
      ./b2.exe --debug-configuration --prefix=./.b2 install toolset=$env:TEST_TOOLSET
